// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUlZRQrKr1dzs0sRXmWdVCl3xzMlYYjPI',
    appId: '1:877013905366:web:68588af46555fcf182fe77',
    messagingSenderId: '877013905366',
    projectId: 'fir-app-67218',
    authDomain: 'fir-app-67218.firebaseapp.com',
    storageBucket: 'fir-app-67218.appspot.com',
    measurementId: 'G-1WGZDXBZEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsHRfO9xNsjwehQgF8dVue_RWRmxnDFjc',
    appId: '1:877013905366:android:63e420b3e9b146ca82fe77',
    messagingSenderId: '877013905366',
    projectId: 'fir-app-67218',
    storageBucket: 'fir-app-67218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0FzInWm0aILetIHaYhn53JjeO3-9rato',
    appId: '1:877013905366:ios:bdcd8ba94989f06982fe77',
    messagingSenderId: '877013905366',
    projectId: 'fir-app-67218',
    storageBucket: 'fir-app-67218.appspot.com',
    iosClientId: '877013905366-285ftreto6vdrkj7dul42k5bufjiipu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0FzInWm0aILetIHaYhn53JjeO3-9rato',
    appId: '1:877013905366:ios:bdcd8ba94989f06982fe77',
    messagingSenderId: '877013905366',
    projectId: 'fir-app-67218',
    storageBucket: 'fir-app-67218.appspot.com',
    iosClientId: '877013905366-285ftreto6vdrkj7dul42k5bufjiipu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUlZRQrKr1dzs0sRXmWdVCl3xzMlYYjPI',
    appId: '1:877013905366:web:659d879e6ed51d6182fe77',
    messagingSenderId: '877013905366',
    projectId: 'fir-app-67218',
    authDomain: 'fir-app-67218.firebaseapp.com',
    storageBucket: 'fir-app-67218.appspot.com',
    measurementId: 'G-BNECGF7E1Z',
  );

}